(() => {
    const CELL_ID = [
        "tilt",
        "one",
        "two",
        "three",
        "four",
        "five",
        "six",
        "seven",
        "eight",
        "nine",
        "zero",
        "minus",
        "plus",
        "backspace",
        "tab",
        "q",
        "w",
        "e",
        "r",
        "t",
        "y",
        "u",
        "i",
        "o",
        "p",
        "brackL",
        "brackR",
        "slash",
        "del",
        "capsLook",
        "a",
        "s",
        "d",
        "f",
        "g",
        "h",
        "j",
        "k",
        "l",
        "dashComma",
        "upperComma",
        "enter",
        "shiftL",
        "leftSlash",
        "z",
        "x",
        "c",
        "v",
        "b",
        "n",
        "m",
        "dash",
        "comma",
        "rightSlash",
        "keyUp",
        "shiftR",
        "ctrlL",
        "win",
        "altL",
        "space",
        "altR",
        "ctrlR",
        "keyleft",
        "keyDown",
        "keyRight"
    ]




    window.data = {
        CELL_ID: CELL_ID 
    }
}) ()

